#!/usr/bin/bash +H
# 3'nd labwork
# $Id: check_2 284 2015-04-16 14:50:54Z korg $

# dir with results for all labs
#TESTDIR=/usr/local/labtest/lab_2/

TESTDIR="$HOME/lcheck/lab_3_tmp"
DIR_WITH_TEST_FILES="/export/labs/lcheck/3/"

# Add up to a full path
STUD_LAB="$2"
[[ "${STUD_LAB:?no script}" == /* ]] || STUD_LAB="$PWD/$STUD_LAB" 

####################### define SCRIPTDIR on release! ########################
SCRIPTDIR="/export/labs/lcheck/enc3/"

#create TESTDIR
mkdir "$HOME/lcheck" 2> /dev/null
mkdir -p "$TESTDIR" 2> /dev/null
panic()
{ 
   echo -e "\rerror: $* " >&2
   rm -rf -- "$TESTDIR" 
   echo "Test failed!"
   exit 1 ;
}

# check_script $variant $script $number_task $test_argument
check_script()
{


   #VAR LAB ARG

   # define stdout & stderr
   OUT=$TESTDIR/test_$3.out
   ERR=$TESTDIR/test_$3.err

   # define stdout & stderr #for norm script
   NORM_OUT=$TESTDIR/norm_test_$3.out
   NORM_ERR=$TESTDIR/norm_test_$3.err
   
   #result diff
   DIFF_OUT=$HOME/lcheck/diff_test_$3.out
   DIFF_ERR=$HOME/lcheck/diff_test_$3.err

   r=1
   i=0
   while [[ $i -lt 4 && $r -eq 1 ]] ;do

   :>"$DIFF_OUT"
   :>"$DIFF_ERR"

   # run student's script
   </dev/null start_lab "${2:?no script}" "$3" > "$OUT" 2> "$ERR"
   # run benchmark script
   </dev/null "${SCRIPTDIR:?nosctipt}/lab3_$1" "$3" > "$NORM_OUT" 2> "$NORM_ERR"
   # check of results presence
   [ -f "$OUT" ] || panic "No output file"
   [ -f "$ERR" ] || panic "No errors file"
   [ -f "$NORM_OUT" ] || panic "No diff output file"
   [ -f "$NORM_ERR" ] || panic "No diff errors file"
   
   # diff check with $arg/out & $arg/err
    /usr/bin/diff -ru "$NORM_OUT" "$OUT" >> "$DIFF_OUT" 2>&1 && \
       /usr/bin/diff -ru "$NORM_ERR" "$ERR" >> "$DIFF_ERR" 2>&1

   r=$(( $r * $? ))
   i=$(( $i+1 ))
   done   
   #panic if differs, so they won't be deleted

   return $r
}

form_arg()
{ 
   cd -- "$DIR_WITH_TEST_FILES"
   for arg in * ; do
      check_script "$2" "$1" "$arg" || \
      panic "Incorrect execution of $1 with argument $arg. 
      See $HOME/lcheck/diff_test_$arg.out and $HOME/lcheck/diff_test_$arg.err"
   done
}
#set -x
echo "$1" | egrep '(^[2-9]$)|(^1[0-2]?$)' > /dev/null || panic "Test run with incorrect arguments."
form_arg "$STUD_LAB" "$1" 

#deleting temp test dir
/usr/xpg4/bin/rm -rf -- "$TESTDIR" "$HOME"/lcheck/diff_test_*
echo -e "\rTest succeeded!                                                                   "     
