#!/usr/bin/bash +H
# 2'nd labwork
# ./2 variant current_testing_script
# $Id: check_2 282 2015-04-16 13:27:30Z korg $

# dir with results for all labs
#TESTDIR=/usr/local/labtest/lab_2/

TESTDIR="$HOME/lcheck/lab_2_tmp"
DIR_WITH_TEST_FILES="/export/labs/2_parameters/test"

# Add up to a full path
STUD_LAB_A="$2"
STUD_LAB_B="$3"
[[ "${STUD_LAB_A:?no script}" == /* ]] || STUD_LAB_A="$PWD/$STUD_LAB_A" 
[[ "${STUD_LAB_B:?no script}" == /* ]] || STUD_LAB_B="$PWD/$STUD_LAB_B" 

####################### define SCRIPTDIR on release! ########################
SCRIPTDIR="/export/labs/2_encoded"

#create TESTDIR
mkdir $HOME/lcheck 2> /dev/null
mkdir -p $TESTDIR 2> /dev/null
panic()
{ 
   echo -e "\rerror: $* " >&2
   rm -rf -- "$TESTDIR" 
   echo "Test failed!"
   exit 1 ;
}

# check_script $variant $script $number_task $test_argument
check_script()
{

   # define stdout & stderr
   OUT=$TESTDIR/test_$3.out
   ERR=$TESTDIR/test_$3.err

   # define stdout & stderr #for norm script
   NORM_OUT=$TESTDIR/norm_test_$3.out
   NORM_ERR=$TESTDIR/norm_test_$3.err
   
   #result diff
   DIFF_OUT=$HOME/lcheck/diff_test_$3.out
   DIFF_ERR=$HOME/lcheck/diff_test_$3.err
   r=1
   i=0
   while [[ $i -lt 4 && $r -eq 1 ]] ;do
   :>"$DIFF_OUT"
   :>"$DIFF_ERR"
   # run student's script
   </dev/null start_lab "${2:?no script}" "$3" > "$OUT" 2> "$ERR"
   # run benchmark script
   </dev/null "${SCRIPTDIR:?nosctipt}/lab2_$1" "$3" > "$NORM_OUT" 2> "$NORM_ERR"
   # check of results presence
   [ -f "$OUT" ] || panic "No output file"
   [ -f "$ERR" ] || panic "No errors file"
   [ -f "$NORM_OUT" ] || panic "No diff output file"
   [ -f "$NORM_ERR" ] || panic "No diff errors file"
   
   # diff check with $arg/out & $arg/err
    /usr/bin/diff -ru "$NORM_OUT" "$OUT" >> "$DIFF_OUT" 2>&1 && \
       /usr/bin/diff -ru "$NORM_ERR" "$ERR" >> "$DIFF_ERR" 2>&1
   # /usr/bin/diff -ru "$NORM_OUT" "$OUT"  && /usr/bin/diff -ru "$NORM_ERR" "$ERR" 
   r=$(( $r * $? ))
   i=$(( $i+1 ))
   done   
   #panic if differs, so they won't be deleted

   return $r
}

form_arg()
{ 
   cd -- "$DIR_WITH_TEST_FILES$2"
   for arg in * ; do
      check_script "$2" "$1" "$arg" || \
      panic "Incorrect execution of $1 with argument $arg. 
      See $HOME/lcheck/diff_test_$arg.out and $HOME/lcheck/diff_test_$arg.err"
   done
}

case $1 in
   1) form_arg "$STUD_LAB_A" 1
      form_arg "$STUD_LAB_B" 2
      ;;
   2) form_arg "$STUD_LAB_A" 3
      form_arg "$STUD_LAB_B" 4
      ;;
   3) form_arg "$STUD_LAB_A" 5
      form_arg "$STUD_LAB_B" 6
      ;;
   4) form_arg "$STUD_LAB_A" 7
      form_arg "$STUD_LAB_B" 8
      ;;
   5) form_arg "$STUD_LAB_A" 9
      form_arg "$STUD_LAB_B" 10
      ;;
   6) form_arg "$STUD_LAB_A" 11
      form_arg "$STUD_LAB_B" 12
      ;;
   *) panic "Test run with incorrect arguments."
esac

#deleting temp test dir
/usr/xpg4/bin/rm -rf -- "$TESTDIR" "$HOME"/lcheck/diff_test_*
echo -e "\rTest succeeded!                                                                   "
