#!/usr/bin/ksh
LANG=en_US.UTF-8

userName=$1
result="/home/s225074/repo/itmo/course3/system_programming_basics/lab3/result"

touch $result 

for num in $(ls -l | cat -n | sed '1d' | awk '{print $1}') 
do
	row=$(ls -l | cat -n | sed '1d' | nawk -v num=$num '$1 == num')
	
	fileName=$(echo $row | awk '{print $10}')	
	user=$(echo $row | awk '{print $4}')	
	group=$(echo $row | awk '{print $5}')	
	fileType=$(echo $row | awk '{print $2}' | cut -c 1)	
	userWritingRoot=$(echo $row | awk '{print $2}' | cut -c 3)	
	groupWritingRoot=$(echo $row | awk '{print $2}' | cut -c 6)	
	otherWritingRoot=$(echo $row | awk '{print $2}' | cut -c 9)

	if [ $fileType = "d" ]
	then
		if [ $(groups $userName 1> /dev/null 2> /dev/null ; echo $?) -eq 0 ]
		then
			if [ $userName = $user ] 
			then
				if [ $userWritingRoot = "w" ]
				then
					echo "./$fileName" >> $result
				fi
			else
				if [ $(groups $userName 2> /dev/null | grep -w "$group" | wc -l) -eq 1 ] 
				then
					if [ $groupWritingRoot = "w" ]
					then
						echo "./$fileName" >> $result
					fi
				else
					if [ $otherWritingRoot = "w" ]
					then
						echo "./$fileName" >> $result
					fi
				fi
			fi	
		fi
	fi
done 

cat $result
rm $result	

