#!/usr/bin/ksh
LANG=en_US.UTF-8

group=$1

for username in `getent passwd | awk -F: '{print $1}' | sort`
do
	if [ `groups "$username" | egrep "$group" | wc -l` -eq 1 ] # it's correctly to use egrep "(^$group$|^$group | $group$| $group )"
	then
		echo "$username "
	fi	
done
