%include "colon.inc"

section .data
colon x11, "11"
db "windowsill", 0

colon x10, "10"
db "flower", 0

colon x9, "9"
db "cinema", 0

colon x8, "8"
db "university", 0

colon x7, "7"
db "frog", 0

colon x6, "6"
db "sand", 0

colon x5, "5"
db "yard", 0

colon x4, "4"
db "England", 0

colon x3, "3"
db "giraffe", 0

colon x2, "2"
db "nurse", 0

colon x1, "1"
db "chief", 0

colon x0, "0"
db "monkey", 0

section .text
